from insights.datapro.api.log import Log
from insights.datapro.api.exception import Exception

log = Log()
exception = Exception()
